### ISSUE TITLE
CEL-seq matrix to seurat

### ISSUE THREAD

**Issue by pbrazda** [yanailab/CEL-Seq-pipeline#16]
I used the CEL-seq pipeline to create an expression matrix. It’s coming from a 384well SORT-seq (CEL-seq2) experiment. Now I would like to feed it to [seurat ](http://satijalab.org/seurat/pbmc3k_tutorial.html) for downstream analysis. 
Do you have any experience with this; what do I need to change in the format of the matrix, what other files I need to feed into seurat?
If you have any other suggestions for the downstream analysis, please let me know. Any guidance or suggestion is appreciated.  

Thanks a lot!

**Comment by Puriney** [comment]
Thanks for using our pipeline. You should refer to Seurat's tutorial: <http://satijalab.org/seurat/immune_alignment.html> which introduce a more general way to load UMI-count matrix instead of 10X, and the key function is `CreateSeuratObject`.

Speaking of the format of the output of our `CEL-Seq pipeline`, you might pay attention to the first column which specifies the gene name and slice it out to store in the `rownames`.

```
#Sample:        BC-1-AGACTC     BC-10-TCACAG    BC-11-AGGATC    BC-12-AGTGCA
ENSDARG00000000001      0       0       0       0       0       0       0
ENSDARG00000000002      0       0       3       0       1       4       7
ENSDARG00000000018      0       0       0       0       0       0       0
ENSDARG00000000019      0       0       0       0       0       0       2
```

Suppose you've read our result and stored as a `data.frame` named `df`. This is a general snippet.

```R
# Gene names become the row names
rownames(df) <- df[, 1]
# Exclude the original first column
df <- df[, -1]
# Load it to Seurat
seurat_obj <- CreateSeuratObject(raw.data = as.matrix(df))
```

**Comment by pbrazda** [comment]
Thank you, I will look into that.
